export const LOADING_CONVERSATION = "LOADING_CONVERSATION";
export const CONVERSATION_LOADED = "CONVERSATION_LOADED";

export const ADD_REPLY = "ADD_REPLY";

export const SELECT_ALL = "SELECT_ALL";
export const UNSELECT_ALL = "UNSELECT_ALL";
export const SELECT_CONV = "SELECT_CONV";
export const UNSELECT_CONV = "UNSELECT_CONV";

export const DELETE_SELECTED_CONV = "DELETE_SELECTED_CONV";
export const DELETE_CONV = "DELETE_CONV";

export const DELETE_MESSAGE = "DELETE_MESSAGE";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
