export const LOADING_CONVERSATION = "LOADING_CONVERSATION";
export const CONVERSATION_LOADED = "CONVERSATION_LOADED";

export const SELECT_MESSAGE = "SELECT_MESSAGE";
export const LOAD_DIALOG = "LOAD_DIALOG";
